export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDDEN_LOADER = 'HIDDEN_LOADER'

export const SHOW_ALERT = 'SHOW_ALERT'
export const SHOW_TOAST = "SHOW_TOAST"
export const PREVIEW = 'PREVIEW'

export const ALL_IMAGES_FROM_USER = 'ALL_IMAGES_FROM_USER'
export const ADD_IMAGE_FROM_USER = 'ADD_IMAGES_FROM_USER'
export const REMOVE_IMAGE_FROM_USER= 'REMOVE_IMAGE_FROM_USER'
export const IMAGE_SELECTED= 'IMAGE_SELECTED'


export const ADD_TOURNAMENT = "ADD_TOURNAMENT"
export const ADD_PARTICIPANT_TO_TOURNAMENT = "ADD_PARTICIPANT_TO_TOURNAMENT"
export const DELETE_PARTICIPANT_TO_TOURNAMENT = "DELETE_PARTICIPANT_TO_TOURNAMENT"


